version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: your_password

  backend:
    image: d1g1tsdocker/foodgram_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    image: d1g1tsdocker/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  gateway:
    image: d1g1tsdocker/foodgram_infra:latest
    env_file: .env
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/staticfiles/
      - media:/media
    ports:
      - 8000:80